name: 'Debian Control File Builder'
description: 'Generate a control file for to be used in the generation of a Debian install package.'
branding:
  icon: 'file'
  color: 'gray-dark'

inputs:
  # Configuration File Path
  config-file:
    description: 'Path to configuration file in JSON format'
    required: true
  # Case Sensitive Keys Boolean
  case-sensitive-keys:
    description: 'True if keys are exactly in the right case, False if keys are to be converted to first letter capitalise, remaining characters lowercase'
    required: false
    default: 'true'
  # Dependency File Path
  deps-file:
    description: 'Path to the file with the list of dependencies to include in the generated control file'
    required: false
  # Desired Output Path
  output-path:
    description: 'The path to where the generated control file will be saved'
    required: false
    #default: "${{ github.workspace }}/output"

outputs:
  control_file_path:
    description: 'The configured path where the generated control file is saved'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - -f
    - ${{ inputs.config-file }}
    - -df
    - ${{ inputs.deps-file }}
    - -o
    - ${{ inputs.output-path }}
    - -csk
    - ${{ inputs.case-sensitive-keys }}