name: Build Example

on:
  push:
    branches: [ master, main ]
  workflow_dispatch:
  
jobs:
  deb-control-file-build:
    name: Generate Debian Package
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
    
      - name: Build Dockerfile Container & Run App in it
        uses: ./
        id: container
        with:
          config-file: 'ExampleFiles/example_control_template.json'
          deps-file: 'ExampleFiles/product_deps.txt'
          
      - name: Prints Output File Path
        run: echo "${{ steps.container.outputs.output_path }}"
        
      - name: Upload Generated Control File
        uses: actions/upload-artifact@v2
        with:
          name: generated-control-file
          path: "${{ steps.container.outputs.output_path }}"
          if-no-files-found: error
