name: Debian-Control-File-Builder

on:
  push:
    branches: [ master, main ]
  workflow_dispatch:
  
jobs:
  deb-control-file-build:
    name: Generate Debian Package
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
    
      - name: Action Test
        uses: ./
        with:
          config-file: 'ExampleFiles/example_control_template.json'
          deps-file: 'ExampleFiles/product_deps.txt'
        
      - name: Upload Generated Control File
        uses: actions/upload-artifact@v2
        with:
          name: generated-control-file
          path: output/control
          if-no-files-found: error
