name: Release Job

on:
  release:
  workflow_dispatch:

jobs:
  release-job:
    name: Generate Debian Package as External Action
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Latest tag
        uses: EndBug/latest-tag@latest